version: "3.3"
services:

  socket-srv:
    image: socket-srv:latest
    build:
      context: ../
      dockerfile: docker/socket-server.dockerfile
    container_name: my-socket-srv
    environment:
      DOTNET_ENVIRONMENT: Docker
    restart: on-failure
    networks: 
      - default
    ports:
      - ${SOCKET_PORT}:6666
    volumes:
      - ./Logs/my-socket-srv:/app/App_Data/Logs
      - ./Upload/my-socket-srv:/app/Upload

  ssl-socket-srv:
    image: ssl-socket-srv:latest
    build:
      context: ../
      dockerfile: docker/ssl-socket-server.dockerfile
    container_name: my-ssl-socket-srv
    environment:
      DOTNET_ENVIRONMENT: Docker
    restart: on-failure
    networks: 
      - default
    ports:
      - ${SSL_SOCKET_PORT}:6667
    volumes:
      - ./Logs/my-ssl-socket-srv:/app/App_Data/Logs
      - ./Upload/my-ssl-socket-srv:/app/Upload

networks:
  default:
    driver: bridge